/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author sala303b
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuPrincipal
     */
    public FormMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        mniCadastrarProduto = new javax.swing.JMenuItem();
        mniCadastrarCategoria = new javax.swing.JMenuItem();
        mnListar = new javax.swing.JMenu();
        mniListarProdutos = new javax.swing.JMenuItem();
        mniListarCategorias = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnCadastrar.setText("Cadastrar");

        mniCadastrarProduto.setText("Cadastrar Produto");
        mniCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastrarProdutoActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadastrarProduto);

        mniCadastrarCategoria.setText("Cadastrar Categoria");
        mniCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastrarCategoriaActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadastrarCategoria);

        jMenuBar1.add(mnCadastrar);

        mnListar.setText("Listar");

        mniListarProdutos.setText("Listar Produtos");
        mnListar.add(mniListarProdutos);

        mniListarCategorias.setText("Listar Categorias");
        mnListar.add(mniListarCategorias);

        jMenuBar1.add(mnListar);

        mnSair.setText("Sair");
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        FormCadProduto form = new FormCadProduto();
        form.setVisible(true);
        
    }//GEN-LAST:event_mniCadastrarProdutoActionPerformed

    private void mniCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        FormCadCategoria form = new FormCadCategoria();
        form.setVisible(true);
    }//GEN-LAST:event_mniCadastrarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnListar;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mniCadastrarCategoria;
    private javax.swing.JMenuItem mniCadastrarProduto;
    private javax.swing.JMenuItem mniListarCategorias;
    private javax.swing.JMenuItem mniListarProdutos;
    // End of variables declaration//GEN-END:variables
}
